//
//  DummyViewModel.swift
//  ProtocolExtraction
//
//  Created by Mohamad Rahmani on 15.01.24.
//

import Foundation

final class DummyViewModel: ObservableObject {
  @Published var firstName: String = ""
  @Published var message: String = ""
}

// to see the `interface` for `DummyViewModel` generated by xcode, just hit cmd + ctrl + up-arrow
// I am going to copy the result over here.
/*
 final internal class DummyViewModel : ObservableObject {

     @Published internal var firstName: String { get set }

     @Published internal var message: String { get set }
 }
 */
